version: 1
disable_existing_loggers: False
root:
  level: DEBUG
  handlers: [consoleHandler, logFileHandler]
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: consoleFormatter
    stream: ext://sys.stdout
  logFileHandler: 
    class: logging.FileHandler
    level: DEBUG
    formatter: logFileFormatter
    filename: ./app.log
    mode: w
    encoding: utf-8
formatters:
  consoleFormatter: 
    "()": colorlog.ColoredFormatter
    format: "%(log_color)s[%(levelname)-7s:%(name)10s]%(reset)s %(funcName)s -> %(message)s"
  logFileFormatter:
    format: "[%(levelname)-7s:%(name)s] %(funcName)s -> %(message)s"
            